-- Ejecutar en Supabase > SQL Editor
-- Borrá este archivo después de ejecutarlo

insert into plans (start_date, end_date, routine, diet_notes, meals_plan)
values (
  '2025-01-01',
  '2026-12-31',
  '[{"day":"DÍA 1 — PUSH","name":"Press banca plano con barra","sets":4,"reps":"6-8","notes":""},{"day":"DÍA 1 — PUSH","name":"Press inclinado con mancuernas","sets":3,"reps":"10-12","notes":""},{"day":"DÍA 1 — PUSH","name":"Aperturas en polea baja","sets":3,"reps":"12-15","notes":""},{"day":"DÍA 1 — PUSH","name":"Press militar con barra","sets":4,"reps":"8-10","notes":""},{"day":"DÍA 1 — PUSH","name":"Elevaciones laterales","sets":4,"reps":"12-15","notes":""},{"day":"DÍA 1 — PUSH","name":"Tríceps en polea con cuerda","sets":3,"reps":"12-15","notes":""},{"day":"DÍA 1 — PUSH","name":"Tríceps francés con barra EZ","sets":3,"reps":"10-12","notes":""},{"day":"DÍA 2 — PULL","name":"Dominadas","sets":4,"reps":"6-8","notes":""},{"day":"DÍA 2 — PULL","name":"Remo con barra","sets":4,"reps":"8-10","notes":""},{"day":"DÍA 2 — PULL","name":"Jalón al pecho en polea","sets":3,"reps":"10-12","notes":""},{"day":"DÍA 2 — PULL","name":"Remo en polea baja","sets":3,"reps":"12-15","notes":""},{"day":"DÍA 2 — PULL","name":"Curl bíceps con barra EZ","sets":4,"reps":"8-10","notes":""},{"day":"DÍA 2 — PULL","name":"Curl martillo con mancuernas","sets":3,"reps":"12-15","notes":""},{"day":"DÍA 2 — PULL","name":"Face pulls en polea","sets":3,"reps":"15-20","notes":""},{"day":"DÍA 3 — LEGS","name":"Sentadilla con barra","sets":4,"reps":"6-8","notes":""},{"day":"DÍA 3 — LEGS","name":"Prensa de piernas","sets":4,"reps":"10-12","notes":""},{"day":"DÍA 3 — LEGS","name":"Extensión de cuádriceps","sets":3,"reps":"12-15","notes":""},{"day":"DÍA 3 — LEGS","name":"Femoral tumbado en máquina","sets":3,"reps":"12-15","notes":""},{"day":"DÍA 3 — LEGS","name":"Hip thrust con barra","sets":4,"reps":"10-12","notes":""},{"day":"DÍA 3 — LEGS","name":"Gemelos de pie en máquina","sets":4,"reps":"15-20","notes":""},{"day":"DÍA 4 — FULL BODY","name":"Peso muerto convencional","sets":4,"reps":"5-6","notes":""},{"day":"DÍA 4 — FULL BODY","name":"Press banca agarre cerrado","sets":3,"reps":"8-10","notes":""},{"day":"DÍA 4 — FULL BODY","name":"Remo con mancuerna un brazo","sets":3,"reps":"10-12","notes":""},{"day":"DÍA 4 — FULL BODY","name":"Press Arnold","sets":3,"reps":"10-12","notes":""},{"day":"DÍA 4 — FULL BODY","name":"Sentadilla goblet con mancuerna","sets":3,"reps":"12-15","notes":""},{"day":"DÍA 4 — FULL BODY","name":"Plancha abdominal","sets":3,"reps":"60seg","notes":""}]',
  'Objetivo: volumen limpio. Superávit moderado (~300 kcal). Alta proteína (2g por kg de peso corporal). Carbohidratos alrededor del entreno.',
  '{"desayuno":"Avena (80g) con leche + 1 banana + 1 scoop whey o 4 claras + café sin azúcar","almuerzo":"Arroz blanco (150g cocido) + pechuga o carne magra (200g) + verduras salteadas + aceite de oliva","merienda":"Yogur griego (200g) + frutas + puñado de frutos secos","cena":"Proteína magra (salmón, atún, pollo, huevos) + vegetales al horno + palta o aceite de oliva","extra":"Post-entreno: batido de whey (1 scoop) + fruta (banana o manzana)"}'
);
